GET http://localhost:9000/subscribe

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "url": "http://tesets",
    "subscriberToTopic": "topic1"
}

###

POST http://localhost:9000/subscribe/madeInLagosxx
Content-Type: application/json

{
    "url": "http://api.madeInLagos.com"
}


###

POST http://localhost:8000/publish/madeInLagosxx
Content-Type: application/json

{
    "ada": {
        "status": true,
        "items": [
            "fish", "books"
        ]
    }
}

###

GET http://localhost:8000/publish


###

POST http://localhost:9000/subscribe/receive/topic
Content-Type: application/json

{
    "data": {"message":"hello"}
}

###

GET http://localhost:9000/subscribe/receive/async