GET http://localhost:9000/subscribe

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "url": "http://tesets",
    "subscriberToTopic": "topic1"
}

###

POST http://localhost:9000/subscribe/topic1
Content-Type: application/json

{
    "url": "http://localhost:9000/test2"
}


###

POST http://localhost:8000/publish/topic1
Content-Type: application/json

{
    "ada": {
        "status": true,
        "items": [
            "fish", "books"
        ]
    }
}

###

POST http://localhost:8000/publish/topic1
Content-Type: application/json

{
    "message": "hello"
}

###

GET http://localhost:8000/publish

###

POST http://localhost:9000/subscribe/receive/topic
Content-Type: application/json

{
    "data": {"message":"hello"}
}

###

GET http://localhost:9000/subscribe/receive/async

###

GET http://localhost:9000/test2